export const vocali = ['a', 'e', 'i', 'o', 'u', 'y', 'à', 'ì', 'ò', 'ù', 'é', 'è', 'h']

export const banned = [
    'di',
    'a',
    'da',
    'su',
    'tra',
    'fra',
    'ho',
    'hai',
    'ha',
    'abbiamo',
    'avete',
    'hanno',
    'sono',
    'sei',
    'è',
    'siamo',
    'siete',
    'io',
    'tu',
    'lui',
    'lei',
    'noi',
    'voi',
    'loro',
    'essi',
    'la',
    'le',
    'e',
    'che',
    'chi',
    'ma',
    'ci',
    'questo',
    'questa',
    'gli',
    'i',
    'mi',
    'ti',
    'vi',
    'se',
    'poi',
    "c'è",
    'piccolo',
    'come',
    'uno',
    'una',
    'però',
]

export const vocabolario = new Map([
    ['yuri', ['yurix', 'willis', 'wilson', 'princess', 'mignolo']],
    ['gianluca', ['zallu']],
    ['gianlu', ['zallu']],
    ['andiamo', ['amuni']],
    [['fatti', 'sotto'], ['appresentati']],
    ['scacchi', ['smacchix']],
    ['carino', ['ducii', 'sapurito']],
    ['arancino', ['arancina']],
    ['arancini', ['arancine']],
    ['matteo', ['matteino', ['piccolo', 'matt']]],
    ['meschino', ['povero']],
])
